### ISSUE TITLE
Use of {date} tag would be much more useful if it included hours and minutes

### ISSUE THREAD

**Issue by grempe** [CtripCloud/docker-make#15]
Currently, if you tag with `{date}` it includes a date of the form `20170701` (YYYYMMDD).

However, if you wanted to use this tag to determine which image to use it only allows you to push maximally once per day, otherwise there will be a conflict between a tag made in the morning, and one made in the afternoon.  You would end up moving the tag.

I would suggest that the date tag should instead include the hours and minutes as well so that even multiple tags per day would be unique (seconds are not needed since its unlikely you have a build system fast enough to do multiple builds per minute. With this form the tags would look like `201707011401` for July 1, 2017 at 2:01 PM UTC.

Lexical sorting is retained for this form as well.

**Comment by jizhilong** [comment]
Great suggestion, actually I think we can extend your idea a little with some capability of  customizing new tag-name sources in `.docker-make.yml`:

```
tag-names:
  - name: datetime
    type: datetime-format
    value: "%Y%m%d%H%M"
  - name: author
    type:  command
    value: "git show -s --format='%an' HEAD"

builds:
  deploy:
    context: /
    dockerfile: Dockerfile
    pushes:
        - 'always=jizhilong/docker-make:{author}-{datetime}"
```
